{"cells":[{"cell_type":"code","execution_count":2,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":10307,"status":"ok","timestamp":1750303379333,"user":{"displayName":"AXEL JESUS SALINAS VENCES","userId":"12418859735922682757"},"user_tz":360},"id":"JRpzUYEnNI5k","outputId":"6fe2e123-3474-400a-e534-e12451bf5467"},"outputs":[{"name":"stdout","output_type":"stream","text":["Requirement already satisfied: flask in /usr/local/lib/python3.11/dist-packages (3.1.1)\n","Collecting flask-ngrok\n","  Downloading flask_ngrok-0.0.25-py3-none-any.whl.metadata (1.8 kB)\n","Collecting twilio\n","  Downloading twilio-9.6.3-py2.py3-none-any.whl.metadata (13 kB)\n","Requirement already satisfied: blinker\u003e=1.9.0 in /usr/local/lib/python3.11/dist-packages (from flask) (1.9.0)\n","Requirement already satisfied: click\u003e=8.1.3 in /usr/local/lib/python3.11/dist-packages (from flask) (8.2.1)\n","Requirement already satisfied: itsdangerous\u003e=2.2.0 in /usr/local/lib/python3.11/dist-packages (from flask) (2.2.0)\n","Requirement already satisfied: jinja2\u003e=3.1.2 in /usr/local/lib/python3.11/dist-packages (from flask) (3.1.6)\n","Requirement already satisfied: markupsafe\u003e=2.1.1 in /usr/local/lib/python3.11/dist-packages (from flask) (3.0.2)\n","Requirement already satisfied: werkzeug\u003e=3.1.0 in /usr/local/lib/python3.11/dist-packages (from flask) (3.1.3)\n","Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from flask-ngrok) (2.32.3)\n","Requirement already satisfied: PyJWT\u003c3.0.0,\u003e=2.0.0 in /usr/local/lib/python3.11/dist-packages (from twilio) (2.10.1)\n","Requirement already satisfied: aiohttp\u003e=3.8.4 in /usr/local/lib/python3.11/dist-packages (from twilio) (3.11.15)\n","Collecting aiohttp-retry\u003e=2.8.3 (from twilio)\n","  Downloading aiohttp_retry-2.9.1-py3-none-any.whl.metadata (8.8 kB)\n","Requirement already satisfied: aiohappyeyeballs\u003e=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp\u003e=3.8.4-\u003etwilio) (2.6.1)\n","Requirement already satisfied: aiosignal\u003e=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp\u003e=3.8.4-\u003etwilio) (1.3.2)\n","Requirement already satisfied: attrs\u003e=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp\u003e=3.8.4-\u003etwilio) (25.3.0)\n","Requirement already satisfied: frozenlist\u003e=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp\u003e=3.8.4-\u003etwilio) (1.7.0)\n","Requirement already satisfied: multidict\u003c7.0,\u003e=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp\u003e=3.8.4-\u003etwilio) (6.4.4)\n","Requirement already satisfied: propcache\u003e=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp\u003e=3.8.4-\u003etwilio) (0.3.2)\n","Requirement already satisfied: yarl\u003c2.0,\u003e=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp\u003e=3.8.4-\u003etwilio) (1.20.1)\n","Requirement already satisfied: charset-normalizer\u003c4,\u003e=2 in /usr/local/lib/python3.11/dist-packages (from requests-\u003eflask-ngrok) (3.4.2)\n","Requirement already satisfied: idna\u003c4,\u003e=2.5 in /usr/local/lib/python3.11/dist-packages (from requests-\u003eflask-ngrok) (3.10)\n","Requirement already satisfied: urllib3\u003c3,\u003e=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests-\u003eflask-ngrok) (2.4.0)\n","Requirement already satisfied: certifi\u003e=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests-\u003eflask-ngrok) (2025.6.15)\n","Downloading flask_ngrok-0.0.25-py3-none-any.whl (3.1 kB)\n","Downloading twilio-9.6.3-py2.py3-none-any.whl (1.9 MB)\n","\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.9/1.9 MB\u001b[0m \u001b[31m34.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hDownloading aiohttp_retry-2.9.1-py3-none-any.whl (10.0 kB)\n","Installing collected packages: flask-ngrok, aiohttp-retry, twilio\n","Successfully installed aiohttp-retry-2.9.1 flask-ngrok-0.0.25 twilio-9.6.3\n"]}],"source":["!pip install flask flask-ngrok twilio\n"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"id":"Lz20HxoEP11T"},"outputs":[{"name":"stdout","output_type":"stream","text":[" * Serving Flask app '__main__'\n"," * Debug mode: off\n"]},{"name":"stderr","output_type":"stream","text":["INFO:werkzeug:\u001b[31m\u001b[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\u001b[0m\n"," * Running on all addresses (0.0.0.0)\n"," * Running on http://127.0.0.1:5000\n"," * Running on http://172.28.0.12:5000\n","INFO:werkzeug:\u001b[33mPress CTRL+C to quit\u001b[0m\n","ERROR:root:Unexpected exception finding object shape\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/google/colab/_debugpy_repr.py\", line 54, in get_shape\n","    shape = getattr(obj, 'shape', None)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 318, in __get__\n","    obj = instance._get_current_object()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 519, in _get_current_object\n","    raise RuntimeError(unbound_message) from None\n","RuntimeError: Working outside of request context.\n","\n","This typically means that you attempted to use functionality that needed\n","an active HTTP request. Consult the documentation on testing for\n","information about how to avoid this problem.\n","ERROR:root:Unexpected exception finding object shape\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/google/colab/_debugpy_repr.py\", line 54, in get_shape\n","    shape = getattr(obj, 'shape', None)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 318, in __get__\n","    obj = instance._get_current_object()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 519, in _get_current_object\n","    raise RuntimeError(unbound_message) from None\n","RuntimeError: Working outside of request context.\n","\n","This typically means that you attempted to use functionality that needed\n","an active HTTP request. Consult the documentation on testing for\n","information about how to avoid this problem.\n","ERROR:root:Unexpected exception finding object shape\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/google/colab/_debugpy_repr.py\", line 54, in get_shape\n","    shape = getattr(obj, 'shape', None)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 318, in __get__\n","    obj = instance._get_current_object()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 519, in _get_current_object\n","    raise RuntimeError(unbound_message) from None\n","RuntimeError: Working outside of request context.\n","\n","This typically means that you attempted to use functionality that needed\n","an active HTTP request. Consult the documentation on testing for\n","information about how to avoid this problem.\n","ERROR:root:Unexpected exception finding object shape\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/google/colab/_debugpy_repr.py\", line 54, in get_shape\n","    shape = getattr(obj, 'shape', None)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 318, in __get__\n","    obj = instance._get_current_object()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 519, in _get_current_object\n","    raise RuntimeError(unbound_message) from None\n","RuntimeError: Working outside of request context.\n","\n","This typically means that you attempted to use functionality that needed\n","an active HTTP request. Consult the documentation on testing for\n","information about how to avoid this problem.\n","ERROR:root:Unexpected exception finding object shape\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/google/colab/_debugpy_repr.py\", line 54, in get_shape\n","    shape = getattr(obj, 'shape', None)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 318, in __get__\n","    obj = instance._get_current_object()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 519, in _get_current_object\n","    raise RuntimeError(unbound_message) from None\n","RuntimeError: Working outside of request context.\n","\n","This typically means that you attempted to use functionality that needed\n","an active HTTP request. Consult the documentation on testing for\n","information about how to avoid this problem.\n","ERROR:root:Unexpected exception finding object shape\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/google/colab/_debugpy_repr.py\", line 54, in get_shape\n","    shape = getattr(obj, 'shape', None)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 318, in __get__\n","    obj = instance._get_current_object()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 519, in _get_current_object\n","    raise RuntimeError(unbound_message) from None\n","RuntimeError: Working outside of request context.\n","\n","This typically means that you attempted to use functionality that needed\n","an active HTTP request. Consult the documentation on testing for\n","information about how to avoid this problem.\n","ERROR:root:Unexpected exception finding object shape\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/google/colab/_debugpy_repr.py\", line 54, in get_shape\n","    shape = getattr(obj, 'shape', None)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 318, in __get__\n","    obj = instance._get_current_object()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 519, in _get_current_object\n","    raise RuntimeError(unbound_message) from None\n","RuntimeError: Working outside of request context.\n","\n","This typically means that you attempted to use functionality that needed\n","an active HTTP request. Consult the documentation on testing for\n","information about how to avoid this problem.\n","ERROR:root:Unexpected exception finding object shape\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/google/colab/_debugpy_repr.py\", line 54, in get_shape\n","    shape = getattr(obj, 'shape', None)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 318, in __get__\n","    obj = instance._get_current_object()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 519, in _get_current_object\n","    raise RuntimeError(unbound_message) from None\n","RuntimeError: Working outside of request context.\n","\n","This typically means that you attempted to use functionality that needed\n","an active HTTP request. Consult the documentation on testing for\n","information about how to avoid this problem.\n","ERROR:root:Unexpected exception finding object shape\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/google/colab/_debugpy_repr.py\", line 54, in get_shape\n","    shape = getattr(obj, 'shape', None)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 318, in __get__\n","    obj = instance._get_current_object()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 519, in _get_current_object\n","    raise RuntimeError(unbound_message) from None\n","RuntimeError: Working outside of request context.\n","\n","This typically means that you attempted to use functionality that needed\n","an active HTTP request. Consult the documentation on testing for\n","information about how to avoid this problem.\n","ERROR:root:Unexpected exception finding object shape\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/google/colab/_debugpy_repr.py\", line 54, in get_shape\n","    shape = getattr(obj, 'shape', None)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 318, in __get__\n","    obj = instance._get_current_object()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 519, in _get_current_object\n","    raise RuntimeError(unbound_message) from None\n","RuntimeError: Working outside of request context.\n","\n","This typically means that you attempted to use functionality that needed\n","an active HTTP request. Consult the documentation on testing for\n","information about how to avoid this problem.\n","ERROR:root:Unexpected exception finding object shape\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/google/colab/_debugpy_repr.py\", line 54, in get_shape\n","    shape = getattr(obj, 'shape', None)\n","            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 318, in __get__\n","    obj = instance._get_current_object()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/werkzeug/local.py\", line 519, in _get_current_object\n","    raise RuntimeError(unbound_message) from None\n","RuntimeError: Working outside of request context.\n","\n","This typically means that you attempted to use functionality that needed\n","an active HTTP request. Consult the documentation on testing for\n","information about how to avoid this problem.\n"]}],"source":["from flask import Flask, request, jsonify\n","from datetime import datetime\n","import json\n","import os\n","\n","app = Flask(__name__)\n","\n","# Archivo de registro simulado\n","LOGS_FILE = \"llamadas_logs.json\"\n","\n","# Función para cargar historial\n","def cargar_logs():\n","    if os.path.exists(LOGS_FILE):\n","        with open(LOGS_FILE, \"r\") as f:\n","            return json.load(f)\n","    return []\n","\n","# Guardar nueva llamada\n","def guardar_logs(data):\n","    with open(LOGS_FILE, \"w\") as f:\n","        json.dump(data, f, indent=2)\n","\n","# Simulación de una llamada al hospital\n","def simular_llamada(hospital, especialidad, nombre_paciente, motivo):\n","    now = datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n","    log = {\n","        \"timestamp\": now,\n","        \"hospital\": hospital,\n","        \"especialidad\": especialidad,\n","        \"paciente\": nombre_paciente,\n","        \"motivo\": motivo,\n","        \"estado\": \"✅ Llamada simulada exitosa\",\n","        \"receptor\": \"Asesor médico especializado\"\n","    }\n","    logs = cargar_logs()\n","    logs.append(log)\n","    guardar_logs(logs)\n","    return log\n","\n","# Endpoint para simular llamada\n","@app.route(\"/api/llamada\", methods=[\"POST\"])\n","def api_llamada():\n","    datos = request.get_json()\n","    hospital = datos.get(\"hospital\")\n","    especialidad = datos.get(\"especialidad\")\n","    nombre = datos.get(\"nombre\")\n","    motivo = datos.get(\"motivo\")\n","\n","    if not all([hospital, especialidad, nombre, motivo]):\n","        return jsonify({\"error\": \"❗Faltan datos necesarios\"}), 400\n","\n","    resultado = simular_llamada(hospital, especialidad, nombre, motivo)\n","    return jsonify({\"mensaje\": \"📞 Llamada simulada realizada\", \"detalle\": resultado}), 200\n","\n","# Endpoint para historial de llamadas\n","@app.route(\"/api/historial_llamadas\", methods=[\"GET\"])\n","def historial_llamadas():\n","    logs = cargar_logs()\n","    return jsonify({\"historial\": logs}), 200\n","\n","if __name__ == \"__main__\":\n","    app.run(host=\"0.0.0.0\", port=5000)\n"]}],"metadata":{"colab":{"authorship_tag":"ABX9TyPzFV1CgODns29r92OXTOPf","name":"","version":""},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}